### ISSUE TITLE
Add logging functionality

### ISSUE THREAD

**Issue by nathan-hess** [nathan-hess/maha-research-utils#3]
**Issue**
Currently, there is no logging functionality of the existing package.  This makes it difficult for users to view code progress and for debugging.

**Possible Solutions**
Implement logger with Python's built-in `logging` package.

**Task List**
- [ ] Define loggers in each file
- [ ] Add logging commands to display errors, warnings, and informational messages
- [ ] Allow user to set logging level using an environment variable

**Additional Notes**
Useful references:
- https://docs.python.org/3/howto/logging.html
- https://docs.python.org/3/library/logging.html
- https://realpython.com/python-logging/
