### ISSUE TITLE
Set up GitHub Actions code quality workflows

### ISSUE THREAD

**Issue by nathan-hess** [nathan-hess/maha-research-utils#5]
**Issue**
Automated checks are not currently implemented, raising chances for introducing errors.

**Possible Solutions**
Set up code quality scanning and automate with GitHub Actions.

**Task List**
- [x] Set up security scanning with Bandit
- [x] Set up linting with Pylint and Flake8
- [x] Test building documentation and check spelling
- [x] Run tests

**Additional Notes**
N/A
