### ISSUE TITLE
Set up Sphinx documentation

### ISSUE THREAD

**Issue by nathan-hess** [nathan-hess/maha-research-utils#6]
**Issue**
For package to be usable by others, it is important to thoroughly document API functions.

**Possible Solutions**
Set up project documentation with Sphinx.

**Task List**
- [x] Configure Sphinx documentation
- [x] Add spell-checking
- [x] Update docstrings for existing code
- [x] Automate documentation-related checks with GitHub Actions (addressed in Issue #5)

**Additional Notes**
N/A
