### ISSUE TITLE
Upload file parsers

### ISSUE THREAD

**Issue by nathan-hess** [nathan-hess/maha-research-utils#7]
**Issue**
Need to upload file parsers, modify file structure to be suitable to work as a Python package, and ensure code is sufficiently robust for general use.

**Task List**
- [x] Upload `simulation_results.txt` parser
- [x] Upload fluid property file parser
- [x] Upload VTK file parser

**Additional Notes**
N/A
